name: Integrated Security Workflow
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Olympix Integrated Security
      - uses: olympix/integrated-security@v0.1.0
            
        
        with:
          args: -f json --no-uninitialized-state-variable --no-default-visibility
