name: Secure Viper

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
  schedule:
    - cron: "0 7 * * 2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Slither
        run: |
          python -m venv /tmp/pip-audit-env
          source /tmp/pip-audit-env/bin/activate

          python -m pip install --upgrade pip setuptools wheel
          python -m pip install slither-analyzer

      - name: Run Slither
        run: |
          source /tmp/pip-audit-env/bin/activate
          slither ./contracts --json slither-report.json

      - name: Upload Slither Report
        uses: actions/upload-artifact@v2
        with:
          name: slither-report
          path: slither-report.json
