name: Security Audit

on: [push, pull_request]

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Slither
      run: |
        pip install slither-analyzer

    - name: Run Slither
      run: |
        slither ./contracts --json slither-report.json

    - name: Upload Slither Report
      uses: actions/upload-artifact@v2
      with:
        name: slither-report
        path: slither-report.json
